### ISSUE TITLE
seems like SUB doesn't set the auxiliary flag correctly

### ISSUE THREAD

**Issue by erbth** [TUM-LRR/Jasmin#31]
Hi,

```
MOV AL, 9
SUB AL, 1
AAS
```

leaves 2 in AL. Shouldn't this produce 8 or am I mixing something up with CPU operation modes?
The thing is on a real machine in real address mode I get 8, like I would expect. No I'm confused.

**Comment by meyerm** [comment]
It's unfortunately correct that Jasmin isn't handling the `AF` correctly in all cases. In `JasminCommand.java`, where the flags are set, I found this nice comment:
> This line is better, but fails in a few cases, e.g.:
> MOV AL, 80h; SUB AL, 18h
> and that can't be fixed easily because the information just isn't there due to
> SUB inverting the second argument and then adding it.

So it's a little bit more work than just fixing a single line of code. Due to the irrelevance of `BCD`, I wouldn't say this is critical. We'll keep this open in case somebody want to step in.

**Comment by meyerm** [comment]
If anybody wants to improve the handling of AF, you're very welcome to reopen this request. But since Jasmin is meant for teaching (and BCD is only mentioned but never used), we'd like to close this for now. Thank you very much for reporting, though!
