### ISSUE TITLE
SUB/CMP sometimes doesn't set CF correctly

### ISSUE THREAD

**Issue by meyerm** [TUM-LRR/Jasmin#39]
The `SUB`/`CMP` commands fails to set the `CF` if the operand is a negative `IMM`:

```
mov al,100
mov bl,-56
mov cl,200

clc
cmp al,-56
; CF ISN'T set

clc
cmp al,bl
; CF is set

clc
cmp al,200
; CF is set

clc
cmp al,cl
; CF is set
```

**Comment by werpat** [comment]
We already had this bug some time ago in #11.
If I remember correctly it was caused by a false size handling of the immediate operand. The fix was reverted in #18, but I cannot remeber which problem it caused.

**Comment by meyerm** [comment]
*facepalm* Yes, you are right and my awesome documentation skills led to a non-existing comment why I reverted it/what didn't work... sorry.

It should have been the fact that operands too big weren't recognized as too big anymore. So a ```mov al,300``` wasn't marked as wrong. I guess by using the operand's size just for the "conversion", it _could_ work without further side effects. Let me try that...

**Comment by meyerm** [comment]
So, does this look better?

**Comment by werpat** [comment]
Yeah, this should work properly. 
I also shortly digged into the code to see why `mov al,300` originally wasn't marked as wrong:

During the validity check of the command the sizes of the first and the second argument are compared (aka `argument[i].address.size`). For this to be correct, the _"real size"_ of the immediate argument has to be calculated. This is **only** done if the size is the default value -1 (_[Parameters.java:259](https://github.com/TUM-LRR/Jasmin/blob/426a9973b120e753709bcde10d647f9caf83c8d3/src/jasmin/core/Parameters.java#L259)_).
Since I had overwritten the size field with the register size, the actual size never got calculated and the check never returned an error.

**Comment by meyerm** [comment]
Yeah, I also followed that path of data. And looking at all the reliance on certain implicit side effects, I'm very reluctant to change the handling at that file.

Thanks for having another look!
