### ISSUE TITLE
Register changes always displayed as 32-bit change

### ISSUE THREAD

**Issue by meyerm** [TUM-LRR/Jasmin#4]
When changing the value of a register, Jasmin paints the changed register values in bold face.

Currently it is always changing the whole 32-bit register (`EAX`) to bold, even when the register view is expanded to show the subregisters and just a subregister (`AX`, `AH` or `AL`) is touched. The values themselves are treated correctly (only change subregisters).

**Comment by atar-axis** [comment]
Let me write down here what I think I understood so far:

1) The function update() in the RegisterPanel.java file calls the update-function for the four "subregisters":

update(jTextField7, value & 0xFFL, dirty);
update(jTextField5, (value >> 8) & 0xFFL, dirty);
update(jTextField2, (value >> 16) & 0xFFL, dirty);
update(jTextField1, (value >> 24) & 0xFFL, dirty);

"dirty" means: the value changed since the last gui-update

since dirty is the same for all the four 8-byte parts, they are all changed equally.
dirty is set some lines before, by:

boolean dirty = data.isDirty(register.aX, doc.getLastStepCount());

Therefore, I tried something like this:

boolean dirtyH = false;
if(register.aH != null){
    dirtyH = data.isDirty(register.aH, doc.getLastStepCount());
}
...
update(jTextField5, (value >> 8) & 0xFFL, dirtyH);


2) This works if you set it "by hand" to false/true. Unfortunately, if you change any part of the register (e.g. by MOV AH, 1), all the other parts are set to "dirty" too.

This happens in the Registers.java : set(...) Function

public void set(Address address, long value) {
	value <<= address.rshift;
	address.shortcut.value = (address.shortcut.value & ~address.mask) | (value & address.mask);
	this.dirty[address.address] = dirtyTimeStamp;
	}

**Comment by atar-axis** [comment]
_I found a solution:_
https://github.com/atar-axis/Jasmin/blob/master/src/jasmin/core/Registers.java
https://github.com/atar-axis/Jasmin/blob/master/src/jasmin/gui/RegisterPanel.java

It's still a very messy - will clean it up a bit and create a pull request if i find some time...

**Comment by meyerm** [comment]
Closed with commit 37607db .
