### ISSUE TITLE
Disrepancy on Carry-Flag

### ISSUE THREAD

**Issue by hbirler** [TUM-LRR/Jasmin#42]
I ran a group of tests with the Carry-Flag both in Jasmin and with nasm & gcc (`nasm -f elf *.asm && gcc -m32 -o demo *.o`).
I tested adding/subtracting positive/negative 8bit numbers resulting in positive/negative results.

```
possibilities:
;0: p-p=p
;1: p-p=n
;2: p-n=p
;3: p-n=n
;4: n-p=p
;5: n-p=n
;6: n-n=p
;7: n-n=n
;8: p+p=p
;9: p+p=n
;a: p+n=p
;b: p+n=n
;c: n+p=p
;d: n+p=n
;e: n+n=p
;f: n+n=n

carry-nasm:
fedcba9876543210
1101010010001110
set: p-p=n & p-n=p & p-n=n & n-n=n & p+n=p & n+p=p & n+n=p & n+n=n

carry-jasmin:
fedcba9876543210
0001100001000010
set: p-p=n & n-n=p & p+n=n & n+p=p
```
The test code: http://pastebin.ubuntu.com/24007505/

**Comment by meyerm** [comment]
Thank you very much for your detailed testing! Unfortunately, it looks like you've used the release 1.5.11 and not the latest `HEAD` in `master`. That version should produce the correct flags.

But if you're okay with it, I'd like to add your assembler file to the repository (f.ex. in `/tests/carry-sub_add.asm`) so that testing becomes easier in the future. If you'd prefer, you could also create a Pull Request on your own and I merge it. As you like.

**Comment by hbirler** [comment]
I can create a pull request tonight after the exam. I'll be careful to use the latest release in the future. Thank you!
